apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowflakes-ingress
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - sf.localdev.iprody
      secretName: snowflakes-tls
  rules:
    - host: sf.localdev.iprody
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snowflakes-service
                port:
                  number: 81

