apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflakes-deployment
  labels:
    app: snowflakes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snowflakes-app
  template:
    metadata:
      labels:
        app: snowflakes-app
    spec:
      containers:
        - name: snowflakes-app
          image: snowflakes:1.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
