spring:
  application:
    name: "Snowflake ID Generator"

snowflake-settings:
  starting-epoch: 946684800
  node-name: ${NODE_NAME}
  node-ip: ${NODE_IP}
  pod-name: ${POD_NAME}
  pod-ip: ${POD_IP}
  worked-id: ${WORKED_ID}

management:
  endpoints:
    web:
      base-path: /management
      path-mapping:
        health: health
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
